- hosts: web
  become: yes

  tasks:
    - name: Install Python and pip
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask

    - name: Copy Flask app
      copy:
        src: ../app/app.py
        dest: /home/ec2-user/app.py
        owner: ec2-user
        mode: '0755'

    - name: Run Flask app
      shell: |
        nohup python3 /home/ec2-user/app.py &
